language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '6'
  - '8'
before_script:
  - npm prune
script:
  - npm run check
  - npm run check:cy
  - npm run unit
  - npm run cy:run
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
